name: Publish Package to npmjs
on:
  push:
    branches:
      - master2
jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  build:
    needs: [run-tests]
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: publish to npm
        run: |
          yarn
          yarn build:all
          yarn publish_to_npm
