name: test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  test-repo:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.set-matrix.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules
            !**/node_modules/@devbro
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cache @devbro packages
        uses: actions/cache@v5
        with:
          path: |
            **/dist
          key: devbro-packages-${{ github.sha }}
      - run: yarn
      - run: yarn build:all
      - name: Generate workspace matrix
        id: set-matrix
        run: |
          WORKSPACES=$(yarn --silent workspaces info | jq -c 'keys') 
          echo $WORKSPACES
          echo "workspaces=$WORKSPACES" >> $GITHUB_OUTPUT

  run-tests:
    needs: test-repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.test-repo.outputs.workspaces) }}
      fail-fast: false
    services:
      redis:
        image: redis:8.2.1
        ports:
          - 6379:6379
        env:
          PORT: 6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
      postgres:
        image: postgres:16.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: dbpassword
          MYSQL_DATABASE: practice_db_1
          MYSQL_USER: dbadmin
          MYSQL_PASSWORD: dbpassword
      memcache:
        image: memcached:latest
        ports:
          - 11211:11211
      rabbitmq:
        image: rabbitmq:4-management
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping || exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: sqs
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          DEBUG: 1
          AWS_DEFAULT_REGION: us-east-1
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    env:
      DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_NAME: testdb
      NODE_ENV: test
      REDIS_HOST: localhost
      MEMCACHE_HOST: localhost
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_URI: amqp://guest:guest@localhost:5672
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: practice_db_1
      AWS_SQS_ENDPOINT: http://localhost:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules
            !**/node_modules/@devbro
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cache @devbro packages
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules/@devbro
          key: devbro-packages-${{ github.sha }}
      - name: run tests
        run: yarn workspace ${{ matrix.workspace }} test
